export const images = {
  phoneIcon: require("../assets/phone.png"),
  backArrow: require("../assets/backArrow.png"),
  nextArrow: require("../assets/nextArrow.png"),
  containerIcon: require("../assets/container.png"),
  cardImg: require("../assets/cardImg.png"),
  dropdownIcon: require("../assets/dropdownIcon.png"),
  calenderIcon: require("../assets/calenderIcon.png"),
  handIcon: require("../assets/hand.png"),
  circular: require("../assets/circular.png"),
  arrowDown: require("../assets/arrowDown.png"),
  binIcon: require("../assets/bin.png"),
  updateIcon: require("../assets/update.png"),
  information: require("../assets/information.png"),
  emoji: require("../assets/emoji.png"),
  doImg: require("../assets/demoImg.png"),
  dontImg: require("../assets/demoImg1.png"),
  cardImgNew: require("../assets/ammee.png"),
};
